### PR TITLE
smartcam motion detector state

### PR DESCRIPTION
**Pull request by daweedm**
#65

### CODE REVIEW

**Comment by daweedm** [comment]
I've got some issues with indentation to pass travis' tests , should be ok now

**Comment by persandstrom** [comment]
Nice!
One thought, are there more configuration parameters that could be useful? would it be good to have a "configuration function" similar to ```set_lock_config``` instead?

**Comment by daweedm** [comment]
Yes, it seems that you can also set the image resolution and enable alerts when someone moved the cam. I'll attend to it this week :)

**Comment by niro1987** [comment]
outdated

**Comment by daweedm** [comment]
> outdated

Indeed, I'm closing it

**Pull request closed without merging**
