### PR TITLE
Update cli

### PR DESCRIPTION
**Pull request by persandstrom**
* Update CLI
* Split cookie login to separate function
* Rename mfa functions

### CODE REVIEW

**Comment by persandstrom** [comment]
@niro1987 Do you mind reviewing?

**Comment by niro1987** [comment]
Will check and get back to you

**Review by niro1987 — APPROVED** [review]
Looks good

**Comment by niro1987** [comment]
I think the cookies need to be refreshed in the request function, so that the request will not fail after the initial cookie has expired.

**Comment by niro1987** [comment]
@persandstrom when do you expect to be able to look into merging these requests? I have some more improvements lined up.

**Comment by persandstrom** [comment]
I'll merge this now and we can look at the cookie expiring in another MR

**Comment by niro1987** [comment]
I already have something setup in a local repo regarding the cookies. I'll create the draft MR once these are merged.

**Pull request merged**
