### PR TITLE
Add possibility to save a session to a file.

### PR DESCRIPTION
**Pull request by tomhur**
Add a posibility to save current session to a file and later load
it so yo don't have to log in every time.

### CODE REVIEW

**Comment by persandstrom** [comment]
Thanks for the PR.
Could you explain the use case for this?
Why do you need to store the session to a file instead of keeping the MyPages instance in a member/global variable?

**Comment by tomhur** [comment]
My home automation system, Domoticz, have some basic support for python. It can trigger scripts based on events or by time. There is not yet any way to save python variables to Domoticz, it's a planned feature.

So in the mean time I need another way to manage the session and implemented this. With this I can have the same session used by different scripts, called from different events in Domoticz, and even one script run by cron.

**Comment by persandstrom** [comment]
I see...
This PR adds a lot of complexity to the library and would need a bit more work to make it compatible with python 2.6 -> 3.5.  

Is it possible to have some sort of wrapper for Domoticz until the python feature is implemented. Maybe use ```shelve``` on the mypages object. 

Example:
```
import shelve
import verisure

with shelve.open('mypages.db', writeback=True) as db:
  if 'mypages' not in db:
    db['mypages'] = verisure.MyPages(
      'login',
      'password')

  try:
    print(db['mypages'].alarm.get()[0].status)
  except Exception as ex:
    print(ex)
    db['mypages'].login()
```

What do you think?

**Comment by persandstrom** [comment]
Pickle on the mypages instance should work as well

**Comment by tomhur** [comment]
Sorry for a late reply. Pickle on mypages instance solves the problem. :)

**Pull request closed without merging**
