### PR TITLE
MFA Login

### PR DESCRIPTION
**Pull request by niro1987**
Adding mfa support for the m-api branch

### CODE REVIEW

**Comment by niro1987** [comment]
> Hi @persandstrom,
> 
> Can you test this please, I'm running into a _"Too may sms sent"_ issue.

I was able to test it, the login seems succesfull but now I'm getting an unauthorized error on other requests so I think I'm not storing the cookies right.

**Comment by niro1987** [comment]
Need to fix login_mfa if device is trusted

**Comment by niro1987** [comment]
#fc3e53c It turns out, that if you try mfa too many times, they don't send sms anymore but you can fall back to email

**Comment by niro1987** [comment]
@persandstrom Please merge #142 first

**Comment by niro1987** [comment]
@persandstrom ready :-)

**Comment by persandstrom** [comment]
Something seems to be not working correctly on Verisure side right now, I'll try this again (hopefully tomorrow)

**Comment by niro1987** [comment]
Thanks!

**Comment by persandstrom** [comment]
Is there a reason why "Trusted device" is not implemented?

**Comment by persandstrom** [comment]
Something is a bit strange. When I try to create a session instance and then call mfa_login I get error 401.

**Comment by niro1987** [comment]
Can you share the response text please.

**Comment by niro1987** [comment]
> Is there a reason why "Trusted device" is not implemented?

I'll have to look into it a bit more. If you trust the device, you'll need to store the trust token and use it on the next login. The cookie alone didn't work for me. It was easier (for now) to just not trust the device and keep the session active with the cookies. I was thinking, let's fix that in 2.5.1 or so.

Also, have a look over at the Home Assistant issues related to the Verisure integration. Lot's of people getting 'too many tokens' error.

**Comment by persandstrom** [comment]
Works like a charm today, thank you for the contributions!

**Pull request merged**
