### PR TITLE
Add camera support

### PR DESCRIPTION
**Pull request by niro1987**
Adding new features to the m-api branch

### CODE REVIEW

**Comment by niro1987** [comment]
@persandstrom I'm interested in hearing what you think of these commits

**Comment by persandstrom** [comment]
Thank you for puttning a lot of effort into this!

Nice to get camera support as well, I believe the only thing missing to be at the same feature level as "master" is MFA   (should not be hard to fix). 

How the overview is constructed is not really according to how I had imagined. The request function can take several query_func results so you would be able to construct an overview request as a combination of small parts. 

I'm currently a bit off but will probably be able to look into this MR thoroughly in the beginning of next week.

**Comment by niro1987** [comment]
Knowing that, with GraphQL, you can manufacture a single overview request, is that (list of many requests) still the way you want to go? I can imagine that a single request would process faster.

**Comment by persandstrom** [comment]
Ah, the request will still only be sent once.

Look at the request function, the list of operations will be concatinated before the request is made.

**Comment by niro1987** [comment]
I'll make the required changes. Do you mind if I format the query strings while I'm at it?

**Comment by persandstrom** [comment]
I think this looks good! All changes here adds value. Could you please update version to 2.4.0 and add a line in the version history, as well. (Readme.md and setup.py), and after that I can merge. Let me think about formatting the strings, it makes them more readable but different from the message cought by the logger. (I have still not tested the additions myself, but will do next week)

**Comment by niro1987** [comment]
Thanks! I'll add the changelog. before I do so, I want to see if I can figure out the MFA and also want to look for a camera stream / record query.

**Comment by niro1987** [comment]
If you want to, I can format the strings while I'm at it anyway.

**Comment by persandstrom** [comment]
MFA is included in the master branch, I believe it works the same way. But I think we should merge this now. Both MFA and camera streams might get messier so let's finish this and start on a new page. I suggest you to focus on the stream first, I don't have cameras and can't add that myself so I would really appreciate camera support!

**Comment by persandstrom** [comment]
Let the strings be unformatted for now

**Comment by persandstrom** [comment]
How do you get the image? Base64 in json?

**Comment by niro1987** [comment]
> How do you get the image? Base64 in json?

Taking the image is a two parts step, first you need to get a requestId, and with it you can make the camera take a picture. 

With the camera query, you get the json pointing to the last picture take. The jpeg file is hosted on the aws cloud. The url to it does not require authentication.

**Pull request merged**
