### PR TITLE
Specialized request

### PR DESCRIPTION
**Pull request by persandstrom**
Remove duplicated code for trying both base URLs
Fix lint warnings
Add giid to all queries (to be able to poll from two installations in one request)

### CODE REVIEW

**Comment by persandstrom** [comment]
@niro1987 Could you please review and test. 
My plan is to make the m-api branch to the "main branch" if we are happy after this MR and upload to pypi.

**Review by niro1987 — COMMENTED** [review]
Personally I would have not chosen for the optional giid, only explicit or with the set method. Because the giid is not returned in the response, so you would have to keep track of which request was made with what giid when making many.

**Review by niro1987 — APPROVED** [review]
Nice refactoring

**Comment by persandstrom** [comment]
> Personally I would have not chosen for the optional giid, only explicit or with the set method. Because the giid is not returned in the response, so you would have to keep track of which request was made with what giid when making many.

Yes, didn't think about that... Makes it a bit messy. The user needs to keep track of the response order (Which I hope is the same as the query order). It would be possible to add giid to each response as well, but I do not know if that is a good idea.

**Comment by niro1987** [comment]
Did you decide on formatting the request strings? That would make it much easier to add or remove a field on the individual requests.

**Comment by persandstrom** [comment]
Nope, I need to contemplate a bit longer :)

**Pull request merged**
