### PR TITLE
Some error in the error handling

### PR DESCRIPTION
**Pull request by lindehoff**
Hi, I noticed that I didn't get the correct error type and I think this will fix it.

### CODE REVIEW

**Comment by persandstrom** [comment]
I think you are right, do you have any way to force the error?

**Comment by persandstrom** [comment]
I raised the error manually and you are definitely correct. I'll merge this and then make some small structure changes to make the tests pass

Thanks

**Comment by lindehoff** [comment]
import verisure
myPages = verisure.MyPages('user', 'pass')
myPages.login()
myPages._session.csrf ="klk"
myPages.alarm.set('pin', 'state')

**Comment by persandstrom** [comment]
Merged, I didn't change the code. set --max-line-length to 100 instead of 80 :)

**Pull request merged**
