### PR TITLE
raise_for_status()

### PR DESCRIPTION
**Pull request by niro1987**
reverse the urls if the first url return a non-200 response so that the same request can be tested on both urls before raising an error.

### CODE REVIEW

**Comment by persandstrom** [comment]
Not really put much thought into this, but would this result in an additional try if the response is for example "Unauthorized Request" ? And if so, would that be an issue?

**Comment by niro1987** [comment]
Yes, any status >= 400 would result in an additional try. Let's say for example that the first url is unreachable (status 500), you would want a new try on the other url.

WIthout this PR, the `except` is never really triggered, because we either return the response `if status_code == 200` or we raise `ResponseError`, which is not included in an `except`.

**Comment by niro1987** [comment]
The last comment on [issue 94028](https://github.com/home-assistant/core/issues/94028#issuecomment-1602508796) shows that the server responded with [504 - Gateway Timeout](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504). This could confirm my suspision that the `SYS_00004` is no longer used and is now replaced with a 504.

**Comment by persandstrom** [comment]
Yes, sounds plausible. Please prepare this with new revision etc in setup and Readme. I can merge it but cannot do a new release to pip until tomorrow or the day after

**Comment by persandstrom** [comment]
Released to pypi

**Pull request merged**
