### PR TITLE
climate history

### PR DESCRIPTION
**Pull request by persandstrom**
New function: Get climate history

usage
```
verisure.climate.get_history('1A2B 3C4D')
```

or
```
python verisure.py user@example.com mypassword history climate '5AC2 4LXH'
```

### CODE REVIEW

**Comment by Risca** [comment]
I was able to pull historical data from my smoke detectors, but not the temperature from the siren. Both smoke detectors and siren are klisted when I do
{code}
python verisure.py user pass get climate
{code}

**Comment by persandstrom** [comment]
Strange, do you get any error?

I get temperature and humidity from the smoke detektors, and temperature from the siren. 

Do see the sirens temperature graph of on mypages?

**Comment by Risca** [comment]
Sorry, false alarm. 'M' and 'W' look awfully alike on my mobile phone :P

**Comment by Risca** [comment]
Okay, did some coding with this and I was wondering if get_history('1A2B 3C4D') is supposed to return 'unicode' type instead of e.g. a list.
    for serial in ['2S5D MHA6', '2ABQ 92ZK', '2ABQ 949U']:
        history = myPages.climate.get_history(serial)
            print type(history).__name__
Will print
    unicode
    unicode
    unicode
I was suspecting
    list

**Comment by Risca** [comment]
Additionally, would it be possible to get climate data for multiple devices in one call?

**Comment by persandstrom** [comment]
Ok! I'll fix both your comments. Will be in about two weeks though.

**Comment by Risca** [comment]
Awesome, can't wait! :D

**Comment by persandstrom** [comment]
@Risca I have made the changes now, any other comment?

**Comment by Risca** [comment]
Just tried it. Seems to work nicely :)

**Pull request merged**
